function downloadRadarData()

EISCAT = 72;
MILLSTONE_HILL = 30;
ARECIBO = 20;
%inst = [EISCAT, MILLSTONE_HILL, ARECIBO];
%instStr = {'EISCAT', 'MILLSTONE_HILL', 'ARECIBO'};
inst = ARECIBO;
instStr = {'ARECIBO'};
beginDatenum = datenum('1966-01-01');
endDatenum = datenum('1995-12-31');

tic;
for i = 1:length(inst)
    filename = [instStr{i},'_',datestr(beginDatenum),'_',datestr(endDatenum),'.dat'];
    downloadInstrument(filename, beginDatenum, endDatenum, inst(i));
end
toc;


end

function downloadInstrument(filename, beginDatenum, endDatenum, instrument)

% globalIsprint('http://cedar.openmadrigal.org/.', ...
%  'YEAR,MONTH,DAY,HOUR,MIN,SEC,GDALT,RESL,PULF,TI,DTI,GDLATR,GDLONR', ...
%  filename, ...
%  'Juho Iipponen', ...
%  'juho.iipponen@helsinki.fi', ...
%  'Finnish Meteorological Institute', ...
%  beginDatenum, ...
%  endDatenum, ...
%  instrument, ...
%  'filter=GDALT,50,200 ', ...
%  [], ...
%  '', ...
%  '') 

globalIsprint('http://madrigal.naic.edu/madrigal', ...
 'YEAR,MONTH,DAY,HOUR,MIN,SEC,GDALT,RESL,PULF,TI,DTI,GDLATR,GDLONR', ...
 filename, ...
 'Juho Iipponen', ...
 'juho.iipponen@helsinki.fi', ...
 'Finnish Meteorological Institute', ...
 beginDatenum, ...
 endDatenum, ...
 instrument, ...
 'filter=GDALT,50,200 ', ...
 [], ...
 '', ...
 '') 

end